runtime: python39
entrypoint: gunicorn -b :$PORT nlp_chatbot:app

instance_class: F2
env_variables:
  GENAI_API_KEY: "AIzaSyAb4CKQ23uIo9PH-FwkGmoB3yHoJHaYuOI"

handlers:
- url: /.*
  script: auto
